name: Ubuntu packaging
description: Build binary .deb package

branding:
  color: orange
  icon: package

inputs:
  flavor:
    description: 'The name of the distribution, i.e. Ubuntu or Debian. Defaults to `ubuntu`.'
    required: false
    default: 'ubuntu'
  dist:
   description: 'The name of a Ubuntu/Debian version, either code name (e.g. jammy) or release (e.g. 22.04)'
   required: true
  platform:
    description: 'The platform to build on. One of `amd64` or `i386`. Defaults to `amd64`.'
    required: false
    default: 'amd64'
  sourcepackage:
    description: 'The name (and relative path) of the .dsc file'
    required: true
  source_dir:
    description: 'The path to the directory that contains the .dsc file (relative to $GITHUB_WORKSPACE).'
    required: false
    default: '.'
  result_dir:
    description: 'The path to the directory where the built .deb files get copied to (relative to $GITHUB_WORKSPACE).'
    required: false
    default: 'artifacts'
  enable_llso:
    description: 'true to enable the llso package repo, otherwise false.'
    required: false
    default: 'true'
  enable_pso:
    description: 'true to enable the pso package repo, otherwise false.'
    required: false
    default: 'true'
  deb_fullname:
    description: 'Full name used for changelog entry'
    required: false
    default: 'SIL GHA Packager'
  deb_email:
    description: 'Email address used for changelog entry'
    required: false
    default: 'undelivered@sil.org'
  prerelease_tag:
    description: 'A pre-release tag to add to the version number'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34 # v2.7.0
    - name: Build image
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
      with:
        context: .
        tags: sil-${{inputs.flavor}}:${{inputs.dist}}-${{inputs.platform}}-${{inputs.enable_pso}}-${{inputs.enable_llso}}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false
    - name: Build package
      shell: bash
      run: entrypoint.sh sil-${{inputs.flavor}}:${{inputs.dist}}-${{inputs.platform}}-${{inputs.enable_pso}}-${{inputs.enable_llso}}
