#!/bin/bash

echo "Hello world! DIST=${DIST}, DISTRIBUTION=${DISTRIBUTION}, PLATFORM=${PLATFORM}, ENABLE_LLSO=${ENABLE_LLSO}, ENABLE_PSO=${ENABLE_PSO}"
echo "INPUT_DIST=${INPUT_DIST}, INPUT_DISTRIBUTION=${INPUT_DISTRIBUTION}, INPUT_PLATFORM=${INPUT_PLATFORM}, INPUT_ENABLE_LLSO=${INPUT_ENABLE_LLSO}, INPUT_ENABLE_PSO=${INPUT_NABLE_PSO}"
echo "INPUT_DEB_FULLNAME=${INPUT_DEB_FULLNAME}, INPUT_DEB_EMAIL=${INPUT_DEB_EMAIL}, INPUT_PRERELEASE_TAG=${INPUT_PRERELEASE_TAG}"
lsb_release -a
